foreground #000000
background #ffffff

background_opacity 1

selection_background #bfbfbf

color0 #000000
color8 #767676

color1 #676767
color9 #888888


color2  #656565
color10 #7e7e7e

color3  #676767
color11 #7f7f7f

color4  #6c6c6c
color12 #8c8c8c

color5  #777777
color13 #8c8c8c

color6  #6d6d6d
color14 #898989

color7  #dddddd
color15 #ffffff

mark1_background #b5b5b5

mark2_background #e2e2e2

mark3_background #b3b3b3

font_family      family="BlexMono Nerd Font" style=SemiBold
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 11

scrollbar never